#include "al/Factory/ActorFactory.h"
#include "al/System/Byaml/ByamlIter.h"

namespace al {

NON_MATCHING // unnecessary streq for mConvertNameData missing
ActorFactory::ActorFactory()
    : mArchive(nullptr)
    , mConvertNameData(nullptr)
{
    mArchive = al::findOrCreateResource("SystemData/CreatorClassNameTable");
    mConvertNameData = new ByamlIter(static_cast<const u8*>(mArchive->getByml("CreatorClassNameTable")));
}

} // namespace al

#include "Game/Enemy/Togezo.h"
#include "Game/MapObj/NoteObj.h"
#include "Game/MapObj/NoteObjGenerator.h"
#include "al/MapObj/FallMapParts.h"
#include "al/Npc/EffectObj.h"
#include "al/Npc/Sky.h"

namespace al {

template <typename T>
LiveActor* createActorFunction(const char* name)
{
    return new T(name);
}

const NameToActorCreator split(sActorFactoryEntries)[] = {
    { "Kinopio", nullptr },
    { "Luigi", nullptr },
    { "Peach", nullptr },
    { "PeachForTitle", nullptr },
    { "BlockDragonGenerator", nullptr },
    { "BombHei", nullptr },
    { "BombHeiGenerator", nullptr },
    { "BombHeiTail", nullptr },
    { "BombHeiTailGenerator", nullptr },
    { "BoomerangBros", nullptr },
    { "Bubble", nullptr },
    { "Bug", nullptr },
    { "Chorobon", nullptr },
    { "ChorobonGenerator", nullptr },
    { "Choropu", nullptr },
    { "Dossun", nullptr },
    { "DossunTail", nullptr },
    { "EnemyCounter", nullptr },
    { "Fugumannen", nullptr },
    { "FugumannenGenerator", nullptr },
    { "GamaguchiKun", nullptr },
    { "Gesso", nullptr },
    { "GhostPlayer", nullptr },
    { "HammerBros", nullptr },
    { "Hoppun", nullptr },
    { "Indy", nullptr },
    { "Kameck", nullptr },
    { "Karon", nullptr },
    { "Killer", nullptr },
    { "KillerGenerator", nullptr },
    { "KillerMagnum", nullptr },
    { "Kuribo", nullptr },
    { "KuriboTail", nullptr },
    { "KuriboTailSearch", nullptr },
    { "KuriboTower", nullptr },
    { "Meragon", nullptr },
    { "Nokonoko", nullptr },
    { "PackunFire", nullptr },
    { "PackunFlower", nullptr },
    { "PackunInk", nullptr },
    { "PataKuribo", nullptr },
    { "Poo", nullptr },
    { "Pukupuku", nullptr },
    { "PukupukuGenerator", nullptr },
    { "PukupukuLoopRail", nullptr },
    { "SamboBody", nullptr },
    { "SamboHead", nullptr },
    { "Sokuten", nullptr },
    { "TentenGenerator", nullptr },
    { "Teresa", nullptr },
    { "TeresaGroup", nullptr },
    { "TeresaRail", nullptr },
    { "TogeMetbo", nullptr },
    { "Togezo", createActorFunction<Togezo> },
    { "Utsubo", nullptr },
    { "Wanwan", nullptr },
    { "WooGan", nullptr },
    { "WooGanSand", nullptr },
    { "Bunbun", nullptr },
    { "BunbunAndPunpunTagObj", nullptr },
    { "BunbunMysteryBox", nullptr },
    { "Koopa", nullptr },
    { "Punpun", nullptr },
    { "PunpunStageDamageFire", nullptr },
    { "BoomerangFlower", nullptr },
    { "Coin", nullptr },
    { "CoinBox", nullptr },
    { "CoinCollect", nullptr },
    { "CoinGathering", nullptr },
    { "CoinGenerator", nullptr },
    { "CoinRailGenerator", nullptr },
    { "CoinRailMoveGenerator", nullptr },
    { "CoinRedStarter", nullptr },
    { "CoinRing", nullptr },
    { "FireFlower", nullptr },
    { "KickKoura", nullptr },
    { "KinokoOneUp", nullptr },
    { "KinokoOneUpFast", nullptr },
    { "KinokoPoison", nullptr },
    { "KinokoPoisonFast", nullptr },
    { "KinokoSuper", nullptr },
    { "KinokoSuperFast", nullptr },
    { "PatapataWing", nullptr },
    { "PropellerBlock", nullptr },
    { "SuperLeaf", nullptr },
    { "SuperLeafSpecial", nullptr },
    { "SuperStar", nullptr },
    { "Telescope", nullptr },
    { "TelescopeTarget", nullptr },
    { "TimerClock", nullptr },
    { "AppearStep", nullptr },
    { "AquariumSwimDebris", nullptr },
    { "BalanceTruck", nullptr },
    { "BeatBlock", nullptr },
    { "BeatBlockHolder", nullptr },
    { "Bird", nullptr },
    { "BlindCloud", nullptr },
    { "BlockBrick", nullptr },
    { "BlockBrickItem", nullptr },
    { "BlockEmpty", nullptr },
    { "BlockHelp", nullptr },
    { "BlockNote", nullptr },
    { "BlockNoteSuper", nullptr },
    { "BlockQuestion", nullptr },
    { "BlockQuestionFlying", nullptr },
    { "BlockQuestionLong", nullptr },
    { "BlockRailCurve", nullptr },
    { "BlockRailStraight", nullptr },
    { "BlockRailTerminater", nullptr },
    { "BlockRoulette", nullptr },
    { "BlockTransparent", nullptr },
    { "BoneRollerCoaster", nullptr },
    { "BridgePukupukuBreakBridge", nullptr },
    { "Burner", nullptr },
    { "Candlestand", nullptr },
    { "CandlestandFire", nullptr },
    { "CandlestandObserver", nullptr },
    { "CourseSelectObj", nullptr },
    { "EntranceCameraObj", nullptr },
    { "FallStone", nullptr },
    { "FireBarCore", nullptr },
    { "FrameOutChecker", nullptr },
    { "Garigari", nullptr },
    { "GeneratorBox", nullptr },
    { "GeneratorBoxHop", nullptr },
    { "GeneratorBoxHopChild", nullptr },
    { "GeneratorEnemy", nullptr },
    { "GoAndReturnParts", nullptr },
    { "Gorori", nullptr },
    { "GororiGenerator", nullptr },
    { "Grass", nullptr },
    { "GrassMike", nullptr },
    { "GroundRiserAttachment", nullptr },
    { "GyroLauncher", nullptr },
    { "JumpFlipBoard", nullptr },
    { "Kabehei", nullptr },
    { "KeyMoveAndFallParts", nullptr },
    { "KickStone", nullptr },
    { "KickStoneStrong", nullptr },
    { "KoopaCollapseStep", nullptr },
    { "KoopaDoor", nullptr },
    { "KoopaDoorLast", nullptr },
    { "KoopaFireGenerator", nullptr },
    { "KoopaPillar", nullptr },
    { "KoopaSwitch", nullptr },
    { "LavaConveyer", nullptr },
    { "LavaGeyser", nullptr },
    { "LiftGeyser", nullptr },
    { "LiftGeyserStep", nullptr },
    { "MarinePlant", nullptr },
    { "NeedleBar", nullptr },
    { "NeedleBarCore", nullptr },
    { "NeedleBlock", nullptr },
    { "NeedleFloor", nullptr },
    { "NeedlePlant", nullptr },
    { "NeedleRoller", nullptr },
    { "NeedleTrap", nullptr },
    { "NutLift", nullptr },
    { "PatanBoard", nullptr },
    { "PatanBoardStarter", nullptr },
    { "PatanBox", nullptr },
    { "PeraObj", nullptr },
    { "PhotoAlbum", nullptr },
    { "Picket", nullptr },
    { "Plant", nullptr },
    { "Pole", nullptr },
    { "PresentBox", nullptr },
    { "RailDotDrawer", nullptr },
    { "RestartObj", nullptr },
    { "Rope", nullptr },
    { "ShadowObj", nullptr },
    { "SpikeStick", nullptr },
    { "StickNeedle", nullptr },
    { "SwingNeedleRoller", nullptr },
    { "SwingSpike", nullptr },
    { "TrampleSwitch", nullptr },
    { "Trampoline", nullptr },
    { "TransparentWall", nullptr },
    { "TreeA", nullptr },
    { "TrickHintPanel", nullptr },
    { "Trilift", nullptr },
    { "UpperBlock", nullptr },
    { "WarpLift", nullptr },
    { "WoodBox", nullptr },
    { "Seagull", nullptr },
    { "SoundEmitObj", nullptr },
    { "NoteObj", createActorFunction<NoteObj> },
    { "NoteObjGenerator", createActorFunction<NoteObjGenerator> },
    { "WarpAreaPoint", nullptr },
    { "WarpCube", nullptr },
    { "WarpPorter", nullptr },
    { "Dokan", nullptr },
    { "WarpDoor", nullptr },
    { "AttackRevolvingPanel", nullptr },
    { "ClockMapParts", nullptr },
    { "CollapseBreakMapParts", nullptr },
    { "CollapseMapParts", nullptr },
    { "FallMapParts", createActorFunction<al::FallMapParts> },
    { "FixMapParts", nullptr },
    { "FloaterMapParts", nullptr },
    { "KeyMoveMapParts", nullptr },
    { "RailMoveMapParts", nullptr },
    { "RollingReflectMapParts", nullptr },
    { "RollingShakeMapParts", nullptr },
    { "RotateMapParts", nullptr },
    { "SeesawMapParts", nullptr },
    { "SlideMapParts", nullptr },
    { "SwingLift", nullptr },
    { "SwingMapParts", nullptr },
    { "SwitchRotateMapParts", nullptr },
    { "SwitchSlideMapParts", nullptr },
    { "VisibleSwitchMapParts", nullptr },
    { "WheelMapParts", nullptr },
    { "WobbleMapParts", nullptr },
    { "Sky", createActorFunction<al::Sky> },
    { "EffectObj", createActorFunction<al::EffectObj> },
    { "EffectObjFollowCamera", nullptr },
    { "EffectObjLiftLiner", nullptr },
    { "EffectObjReEmit", nullptr },
    { "EffectObjSensor", nullptr },
    { "EffectObjStream", nullptr },
    { "EffectObjSwitch", nullptr },
    { "WaterFlowCube", nullptr },
    { "StreetPassObj", nullptr },
    { "DemoStarter", nullptr }
};

} // namespace al
